image: docker:18

# The services element defines additional Docker images which are 
# linked to the main container. In this case the main container 
# is a plain Docker image while the linked container is enabled 
# for running Docker in Docker 
services:
  - docker:dind

variables:
  IMAGE_VERSION: 0.6.10
  DOCKER_DRIVER: overlay
  BASE64_YAML: ''
  MANIFEST_TO_APPLY: ''
  #  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

cache:
    paths:

build:
  image: python:3.5
  stage: build
  script:
  - python list.py
  artifacts:
    paths:

package:
  stage: package
  script:
    -  docker login -u nelsonv -p 123456
    -  docker build -t nelsonv/python:0.1 .
    -  docker push nelsonv/python:0.1
      


